PATH_MSAS: /data/msas-pangeblocks/msas-diagonals
#/data/msas-pangeblocks/mini-experiments/

# test/alpha
# "/data/msas-pangeblocks/sars-cov-2"
# "/data/msas-pangeblocks/sars-cov-2"
# "/data/msas-pangeblocks/sars-cov-2"
# "/data/msas-plasmids/fftnsi-op1.53-ep0.123" 
# "/data/plasmids/target-fasta/seqs-for-msa"
# "/data/alessia/covid/big-msa" 
# "test" 
# "/data/msas-pangeblocks/HLA-zoo/no-reverse-complement/mafft.op5-ep0"
#"/data/alessia/covid/small-msa" 
#"/data/msas-pangeblocks/HLA-zoo/no-reverse-complement/mafft.op5-ep0" #

# Format: /path/to/directory/<name-experiment>-<standard/row-maximal>-decomp-<not>-alpha-consistent
PATH_OUTPUT: /data/analysis-paper/experiments/msas-diagonals-not-decomp-not-alpha-consistent
# /data/analysis-paper/experiments/mini-experiment-standard-decomp-not-alpha-consistent
# /data/analysis-paper/experiments/alpha-consistent 
# "/data/pangeblocks-experiments/sars-cov-2"
# "/data/pangeblocks-experiments/plasmids-fftnsi"
# "/data/pangeblocks-experiments/covid/small-msa" 
# "/data/alessia/covid/output-big-msa"
# "output-test-grid"
# "/data/pangeblocks-experiments/pbwt/HLA-zoo-pangeblocks/output-HLA-zoo-mafft.op5-ep0" 
#"/data/alessia/covid/pangeblocks-small-msa-wildpbwt" 
# "/data/pangeblocks-experiments/HLA-zoo-pangeblocks/output-HLA-zoo-mafft.op5-ep0"

OPTIMIZATION:
  OBJECTIVE_FUNCTION:
    - "nodes"
    # - "strings"
    # - "weighted"
    # - "depth"
  PENALIZATION: # used only with "weighted" and "depth"
    # - 3
    # - 5
    # - 7 
    # - 100
    # - 500
    - 1000
  MIN_LEN: # used only with "weighted"
    # - 10
    # - 20
    # - 30
    # - 40
    - 50
  MIN_COVERAGE: # used only with "depth"
    # - 0.1
    # - 0.2
    - 0.3
  THRESHOLD_VERTICAL_BLOCKS: # minimum length of vertical blocks to be fixed in the optimal solution
    # - 1 
    # - 5
    # - 10
    # - 15
    # - 20
    - 25
    # - 30
    # - 35
    # - 40
    # - 45
    # - 50
    # - 53837
  TIME_LIMIT: 180 # time limit to run each ILP (minutes)
LOG_LEVEL: "INFO"
THREADS: 
  TOTAL: 16  # smk
  SUBMSAS: 1 # ThreadPoolExecutor; 1 -> for loop
  ILP: 8    # gurobi threads
DECOMPOSITION:
  STANDARD: False
  ALPHA_CONSISTENT: False
USE_WILDPBWT: True
# to compute maximal blocks, otherwise SuffixTree will be used
# standard decomposition . If False, use row-maximal-decomposition