PATH_MSAS: "msa-difficile"
PATH_OUTPUT: "output-msa-difficile-strings"
OPTIMIZATION:
  OBJECTIVE_FUNCTION: "strings" # nodes, strings, weighted
  PENALIZATION: 3 # used only with "weighted"
  MIN_LEN: 2 # used only with "weighted"
LOG_LEVEL: "ERROR"