PATH_MSAS: /data/msas
PATH_OUTPUT: /data/output
OPTIMIZATION:
  OBJECTIVE_FUNCTION:  # list of objective functions to try
    - "nodes"
    - "strings"
    - "weighted"
    - "depth"
    - "depth_and_len"
  PENALIZATION: # used only with "weighted" and "depth"
    - 1000
  MIN_LEN: # used only with "weighted"
    - 15
    - 20
    - 25
    - 30
  MIN_COVERAGE: # used only with "depth"
    - 0.11
    - 0.3
    - 0.5
  THRESHOLD_VERTICAL_BLOCKS: # minimum length of vertical blocks to be fixed in the optimal solution
    - 1
    - 2
    - 8
    - 16
  TIME_LIMIT: 240 # time limit to run each ILP (minutes)
LOG_LEVEL: "INFO"
THREADS:
  SUBMSAS: 1 # ThreadPoolExecutor; 1 -> for loop
  ILP: 8     # gurobi threads
DECOMPOSITION:
  STANDARD: True          # True: use complete decomposition of blocks | False: use row-maximal decomposition of blocks
  ALPHA_CONSISTENT: False # True: use an alpha consistent decomposition of blocks
USE_WILDPBWT: True

# When spliting the MSA into subMSAs, they will have at most this number of cells/positions 
# this will limit the number of constraints used by the ILP. Eg: 100 rows x 1000 columns = 100000 positions
MAX_POSITIONS_SUBMSAS: 100000 # 200000 Row-maximal | 100000 Complete

# Maximal blocks with at least the following number of rows and columns will be fixed in the solution
MIN_ROWS_FIX_BLOCK: 0
MIN_COLS_FIX_BLOCK: 0