from .block_decomposition_row_maximal import block_decomposition as block_decomposition_row_maximal
from .block_decomposition_complete import block_decomposition as block_decomposition_complete
from .block_decomposition_standard import block_decomposition as block_decomposition_standard